[package]
name = "hastur_macro"
version = "0.1.0"
authors = ["Alexey Aristov <aav@suprematic.de>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
